# The variant hub defines all past and current modeling tasks in a single JSON.
tasks_url: https://github.com/reichlab/variant-nowcast-hub/raw/refs/heads/main/hub-config/tasks.json

# These fields must match our official registration details in the hub's
# metadata.
hub_team_name: blab

# Define list models to submit to the hub.
hub_models:
  - data_provenance: gisaid
    variant_classification: nextstrain_clades
    geo_resolution: usa
    model: mlr
