# The variant hub defines all past and current modeling tasks in a single JSON.
tasks_url: https://github.com/reichlab/variant-nowcast-hub/raw/refs/heads/main/hub-config/tasks.json

# These fields must match our official registration details in the hub's
# metadata.
hub_team_name: blab

# Define model parameters indexed by model abbreviations to use for hub
# submission.
hub_models:
  open_hier_mlr:
    data_provenance: open
    variant_classification: nextstrain_clades
    geo_resolution: usa
