name: Open SARS-CoV-2 clade counts

on:
  repository_dispatch:
    types:
      - clade-counts
      - open/clade-counts
      - genbank/clade-counts
  workflow_dispatch:
    inputs:
      slack_channel:
        description: 'Slack channel to push update alerts. Default channel is nextstrain-counts-updates.'
        required: false
      trial_name:
        description: 'Short name for a trial run. WARNING: without this we will overwrite files in s3://nextstrain-data/files/workflows/forecasts-ncov/open'
        required: false

jobs:
  set_s3_dst:
    runs-on: ubuntu-latest
    steps:
      - id: s3_dst
        run: |
          S3_DST=s3://nextstrain-data/files/workflows/forecasts-ncov

          if [[ "$TRIAL_NAME" ]]; then
            S3_DST+=/trial/"$TRIAL_NAME"
          fi

          echo "s3_dst=$S3_DST" >> "$GITHUB_OUTPUT"
        env:
          TRIAL_NAME: ${{ inputs.trial_name }}
    outputs:
      s3_dst: ${{ steps.s3_dst.outputs.s3_dst }}

  open_clade_counts:
    needs: [set_s3_dst]
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: aws-batch
      run: |
        nextstrain build \
          --cpus 8 \
          --memory 16gib \
          --env SLACK_TOKEN \
          --env SLACK_CHANNELS \
          --env S3_DST \
          ingest \
          upload_all_sequence_counts \
          --config data_provenances=["open"] s3_dst="$S3_DST"
      env: |
        SLACK_CHANNELS: ${{ inputs.slack_channel || vars.SLACK_CHANNELS }}
        S3_DST: ${{ needs.set_s3_dst.outputs.s3_dst }}

  trigger_model_runs:
    needs: [open_clade_counts]
    if: ${{ !github.event.inputs.trial_name }}
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run run-models.yaml --repo nextstrain/forecasts-ncov -f data_provenance=open
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_WORKFLOW_DISPATCH }}
